ext: Zero-init `ext/softfloat` `commonNaN` macros (#3038)
Clang 21 added `-Wuninitialized-const-pointer` (and we build with
`-Werror`). With `SOFTFLOAT_FAST_INT64` the various `*ToCommonNaN`
macros never write to the destination struct, so the new check fires:

```
ext/softfloat/extF80_to_f128.c:64:45: error: variable 'commonNaN' is
uninitialized when passed as a const pointer argument here
[-Werror,-Wuninitialized-const-pointer]
 64 | uiZ = softfloat_commonNaNToF128UI( &commonNaN );
    |                                       ^~~~~~~~~
```

See the source here:

https://github.com/gem5/gem5/blob/7a2b0e413d06c5ce7097104abef3b1d9eaabca91/ext/softfloat/extF80_to_f128.c#L64.

The lastest version of softfloat does not fix this error (The project
hasn't been updated in 2 years with most of remaining unaltered for the
last 9 years). Therefore I have opted to modifiying the code in
`ext/softfloat`.

Thechange alters the macro which creates the struct to zero the
`commonNan`. This change alters ever `*ToCommonNaN` macro to
zero-initialise the struct. This preserves behaviour while satisfying
clang 21.